services:
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mini-e-wallet-emulator
    ports:
      - "5433:5432"
    networks:
      - mini-e-wallet-emulator
    volumes:
      - ./postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 2s
      retries: 20

  server:
    build:
      context: ./server
      dockerfile: dockerfile
    container_name: server
    restart: always
    ports:
      - "2412:2412"
    networks:
      - mini-e-wallet-emulator
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./server/.env.production.local
    volumes:
      - ./static:/static

  client:
    build:
      context: ./client
      dockerfile: dockerfile
    container_name: client
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env.production.local
    networks:
      - mini-e-wallet-emulator
    depends_on:
      db:
        condition: service_healthy

volumes:
  db:

networks:
  mini-e-wallet-emulator:
