services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prisma-postgres
    ports:
      - "5433:5433"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
