services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mini-e-wallet-emulator
    ports:
      - "5433:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data

volumes:
  postgres:
